### ISSUE TITLE
Fails to get header

### ISSUE THREAD

**Issue by logicmason** [JesseHerrick/jekyll-on-rails#1]
I just cloned the repo, bundle installed (after bundle update ffi), and started the server. The jekyll build fails:

```
Configuration file: /Users/me/projects/jekyll-on-rails/config/jekyll.yml
  Liquid Exception: Failed to get header. in _posts/2015-03-27-welcome-to-jekyll.markdown
E, [2015-10-08T13:08:24.018931 #22833] ERROR -- : Jekyll site build failed.
```

**Comment by JesseHerrick** [comment]
Thanks for reporting this. I ran `bundle update` and everything is working now. You can also just pull and `bundle`.
